defmodule Quest2 do
  defp input1 do
    # """
    # WORDS:THE,OWE,MES,ROD,HER

    # AWAKEN THE POWER ADORNED WITH THE FLAMES BRIGHT IRE
    # """

    """
    WORDS:LOR,LL,SI,OR,EC,RU,IS

    LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMMODO CONSEQUAT. DUIS AUTE IRURE DOLOR IN REPREHENDERIT IN VOLUPTATE VELIT ESSE CILLUM DOLORE EU FUGIAT NULLA PARIATUR. EXCEPTEUR SINT OCCAECAT CUPIDATAT NON PROIDENT, SUNT IN CULPA QUI OFFICIA DESERUNT MOLLIT ANIM ID EST LABORUM.
    """
  end

  defp parse(input) do
    ["WORDS:" <> words, phrases] = String.split(input, "\n", parts: 2) |> dbg()
    {String.split(words, ","), String.split(phrases, "\n", trim: true)} |> dbg()
  end

  def part_one do
    {words, [phrase]} = parse(input1())
    part_one(phrase, words, 0)
  end

  defp part_one("", _, acc), do: acc

  defp part_one(<<c::utf8, rest::binary>> = phrase, words, acc) do
    case Enum.find(words, &String.starts_with?(phrase, &1)) do
      nil -> part_one(rest, words, acc)
      w -> part_one(rest, words, acc + 1)
    end
  end

  def input2(:test) do
    """
    WORDS:THE,OWE,MES,ROD,HER

    AWAKEN THE POWE ADORNED WITH THE FLAMES BRIGHT IRE
    THE FLAME SHIELDED THE HEART OF THE KINGS
    POWE PO WER P OWE R
    THERE IS THE END
    """
  end

  def input2(:real) do
    """
    WORDS:EI,G,J,YEN,NVRKNILMYZ,KCV,HV,YARV,IVSXJQUVQI,HZKPLCGZNE,CJAC,CWOBIGSRBE,YOOI,IQCKAXPNPW,OJWJFZGWJZ,AKML,XDFO,AB,VX,ZKTQ,OW,DL,HNJ,YGIZXOZREH,YZTR,PJ,FXMNMLKLFF,QCX,CGB,LM,UOH,GAKK,KP,AZ,QOBRSGPMKT,XKOQ,ZJO,SZH,X,PAC,L,WOW,ZK,OO,F,PNB,XZOFVKXRYK,MSYH

    QKWYJJWYMONBDVPXAZEVCNTFYTJMOKVUNFBXUIUP
    PZJAYDKCHI
    JAWFZDOEBIZYARGQKHZZALVVFLFYCUBOLJZTZHLVMAAPSVTAEFDQNTVASDLA
    THWZZEGZBB
    QHGSWCYQYDNTGVAORQYD
    EYGBPORRGGBJVTVEXMBSNLYBIMXNYIXPYQBRUWLSVFZRXMSRPBDTJLHBBTWK
    RINDTCXOMPIIOWCLIQPF
    ZPGCJWLCUSKUUKZTZXTRVHVAEWHGYOTBFRNSXFPY
    MKZAXGNUTAYTZRCORWTELONITHJQIPJQDSKNFMWFXVFOZGCAEI
    CJHVCFOZGYGEPTYXTGXLVSXRCHKVREAEFZCFHCWSKDOFHKXBBOIIDAROEHLR
    VZQIYWCUEQ
    TXHAAZWWHHTJPRAHNXPHBTZJGRPDGKEDPFQKDKCXLZWEFOOGZV
    HBUTVGXURZEHOOOTMFIVCGCUIWUCIIHOCEXITWCW
    YSDXMSOYDDVSAGROGXUVZJXQACAKMUAJMTUGLRZK
    CJDCKIPXOWFZDMENBHVB
    HBAOPREGAEOYRSCDRVCETCUSPVVAHVAMGBJFFVYM
    RKOQKPCMLTVCASYIUUELFGAMVJBVOKNMQGKFTDTGPDYPDFXMHDHSWSGTZRVQ
    DUAHSXSJBJQWIDCLYVTW
    IEUDYIIOJRYCQDISDIUTHFKBFTKMRRULYWFQRUFHEMMOLOUIWXIDDJFUZGLM
    MLNWTSDSVTTPLTPTVUQGGZZQXHLAET
    RPKGVQWKMFHYKZPOGUDPTETLDRUWRITRVXRAUNCC
    QERASDFASDVOOOASDCYWECVY
    XFBVNCUQEPOSJIHFJBPOMSXZQOKXPGPBIGIFEKEXTBBOZOMDVORTKFLCZZNW
    HVMNFRRBPA
    ISNWISCYIGBBISLRGQJRSRSFOQHVVWQZWOLHMDPLUTRZESUVXVWDYFIRSHAH
    EVDFNDZFCYVBGGHLCAJZBYGSVQFKXRYMFNXNNTEMHJLJKZDOYXLJAAKLPRID
    YXKMCMFJMSXLPTURNMNSUQGYWQRJCAXRTUTRTQHLEHKGVOALBA
    BQOELKENDXMOGVVRRSADKALYOJHBHKRUVMXASYPZ
    HROEQHOIMBFGWPUEYPZTONLINUPVPIUTHEVWOVFO
    GGHZRNCGDRDZYJOTIZFQMTUOQOKZVG
    LNFPOAGSDFCNXUQTCEOAVEBCIIDBFI
    FMHGTZTMDDGWVKYCVYEKFPZAZIXZLOFUXCRHNXKE
    ZCFNVGXCEEMZUHBJTOPXCTTKGLBZRPPRXRATLPUL
    VSDOQVGIVCJJKYLLQTLSKNAWKYHSMVXHRDENKDGZCFAPFTHUIRVKQUGXTQRS
    EORXAWTMMNXZWREDLHXVPFUYCJLBLQWNODOPQNCN
    KTYMMYATIG
    MUMZGNYHJNYVBJPRQGLJDXIIHGGGAU
    ZQZEKIBQAUSDGBUOIHIVRMNRFVEUCM
    SSHIWPTWIALWEDXVVOFY
    WHHVWCTMLUZGCSWDKYBNXILTYGWCWFLVAUYDEJBX
    HIGESYHPDL
    CLRMISBTZJ
    JIWPGPGZPEXTVBVFXNZXZUFIEQDHVN
    KVRSIQQHIJMBUSIUFKBD
    TAHABULZHDSIDNDEIKTOJURVUCNWUO
    BLCWCQLEYCSPDHUULLOIYQVIEACQCFPKKSUOTTQT
    YSSRPBTYTR
    GJFFTZFFIUMFZOGODDBDEJUCFLTBSI
    CNATJTCLMJHUVNXVHPCQPJZOASWNXQNBGSYPJKOH
    KQNDQJTMLMMWPRPNVESPPYDHUJOATWKFBZJTOXRLWYCTQOFWIS
    BBLJZMYCUTLVISSBNWPZTIPNEUVUQD
    WYXZFAXFGCRTQMGVPZMZ
    LPNEKGRWMNUYCOABFRWKYQYWFFKLIY
    EBVRBQUAUPUOYZGZVVCLECKDOQGWPVDAQLOTBDHFWNZGUCYBPZDTFAXUMCWO
    LORSMKVXPLJRDHHXVDFXNMCXCLNAKM
    BIUUVHQTWZGGRGKBZDFXCUVQTHATRDDVXKXJOGBM
    SDZPOGOQHMYJIGAESEJF
    FJLGVABWTD
    VIYNPXTWEPILAGKMJDAHQKEGXTROVK
    QDMANTPFJBLZUQVBEBJKHPRFSUAVLHRZKLFVDCNAJBWBBOCMGG
    XHBXAUMJZPFXROXCAYYU
    SGOGEHDIFTDFSPWOYFFURBEDXRBXPC
    CRQDQKHVEMHDYDSKWAQTSEMNUQJZAJVSICOMPVWVEVYLFIRPYYEOFDRQRIDY
    XGUINMIBVPEYPJNEMEOW
    LMHONUAMKAYOYWDOVUIONUHLYKLMPWWIWRBRMDTKEWUYLEJJRKOTTFURRFIF
    YEFQHNUQPMFCWIYVDINVSRKYXDOABEJZQOUMKJZNMHQAAVOIGL
    KNNESSOFASQRKZPSVKBM
    LIVRSLHTFTGZTDABXLHIQPFGEEBJJB
    ZHPKCKXZJUKMYXLYZERI
    GXHBYFNQFPBYXSFDWYPXJBRYBYBQBPFNYHRHTMVQ
    EEFYMYIVZYPAAMTTYVRUGJSBOKATFUICFOWFRXCE
    QEYRUGATFGASDFOOOCVYACAYCV
    PZFKZCYULZBNMBWHWUXQEQGARVGCGFMFCFRCMNNMHCWTDKZWJDTYCGLDLXLS
    OYHZVOUQRVXALTMTZRKR
    IJDOYAXCGWELTEMCHMMQJQPZNXFNEJIYNGHBRMYH
    ILFGEJVJDDAYHVAAEJNBRHEZJLAGLBZGSMANUZGMCIJANEAYDU
    UJVZNJTDNMUKDVMWLPOCUUGPIUTOLM
    WIOJCSIWNYLRDOJNAPGRBNAGHVBZUGDUMIRYBQUL
    CDSLNQLXUFTPFMSUQYJTDTLJBTWFGGNNETKWGHEAZEJNCQNBTU
    MDBNVRSJOFRFIZOIPRTNCNQAXKQXJE
    HUCFDYLLWCRQAXFVSNFO
    QTLXGASILSJADIJRBYCCJYQYAVFBZDWTYJKIMDYWELBQZUNUAORXCEDJGWJY
    JMUXRMHUPXQWXBNFNEEQCUXWCWAOYD
    BJQLFBOAGR
    XPUBDJFBIPYMFUYLWVVWRPWTXOBTLC
    URUARZDOPSRHUDZTUUFSDQOTCWSAJSMDHNDJYGCO
    BXCSVEOFBQZZFZJFBFMCCUBQWCODUF
    NQGUYHAYITNNDTEZTQRAVLLQEPMFNERQGPDYECLTLDFMMQCGBSPZDPCKWMXN
    QEHJHICICLKPVGUNZIIG
    XLXFPSSYNRFZYNSBHHQV
    IGBBRTRLEU
    ISSCEBIUGIKOFEJGBYST
    SXZBCTHJUY
    QIXYBFPAZQXFJEKYZMJW
    PFSNOIVIYP
    KDBQMWJWPZMJKKPJFWJRNNUGPUMZTG
    LYGHLWYWBNIZEVNGAEPGBMQFJBNYXOSBKYWGKJNJOIJFIWFMKLRMSIVAXCJO
    EZTTQWGHHDNVOVFNIIYIYNGPFEMYNMUUPDWTZVLBFSYATZNYRFKCQXRFIUWR
    NJPODVUOKJ
    JODFBKWKWAWFIOUCQYSJUOEHWCTXRWTJIRZOEUCB
    BLZBMRWTWN
    EJOGIOJTDRBPVQQDEWMQIPCMRJPBOAKOZONYNQZCKRSVPWUVXMNTSSQYYNWM
    MKJFYWKXWCYUCUWDEMTJ
    REKKAWYUMYCRCKZRNHMWPVRVVQHLCSKVOFCHIHPLAFXSFIYNTG
    NJDWDTMWAEKYTJITIDLPKPXNMFCXNMZRZXYVBKWGLDJCWNILNXHPOJDZYUTM
    QNYUEJOOVF
    DWBQQFSTADMMRXSJEEKHZGBJISAKFY
    YURBDYPYJF
    JZWZSKSPCOISBIDBGIYXJUKOONRETRGZPUIWNUVXTBYLKYEOAA
    OIGUGIQAJVSHHIRMJBWNIOMGDWBOLY
    HXATELXJXPMRKQKHQNFEFSZMFUXOSC
    DVQBSYJRSWOMTWKNOVST
    PTJOYEXJQB
    NZYTZUIECNSQSYWZQORZGDMIEULDDZQRFYCJOXVHUBPOZAVMAI
    RVMRDISPDGUUJDRCKLAPAJQWUPERTV
    XSCRIQZYVMOULIHISQESJDMLMJEXFOZZWHLSMXCZFRQILTSSHF
    NUGRCCKPOMSIYZKVWMOEEWLHJPJYGLHWXMGYEOQEUTRHVSSGVO
    VMQJXJEXOY
    QWZBPKIHAJJIQHYPIVVOEDILHLGFIIZDIOMSQTXSZVBEPPGMYOMEEYIQOYIL
    AVJIKURPESYFJFITPKOZSXWZXUAXJSBDFQLZJXYEOGRIAPOSGLUNUQVUZDLQ
    YBBDGCBYOW
    MMNECTAYYHWVCNKBRLIY
    XLXPIGWUMN
    YWNDZMDTHRWMBEGSHKCGLQQSYSBIXA
    PLTCWXPEMEHWXMVITBWMYBLPDTSHCGSEAOMHOIPQ
    DEGWUPNBOR
    KDVDJSVRRGZUMHULKVVTIPZJCYZCAE
    FJBQVOHPZWNRGKHFNCPRHYOULOFOOJYIFIIOLJKSVZOGIRLVLMZXAYONUGCD
    TYCOJPTDEL
    OKWZTQRIODHAXGJNJSPFQYBLRSECWRXYAJBXKBTH
    VRZYSIJBSNQJHMCQOETMDFAVYDLXLGHGWPHCHSWJOYDIHGWYMXCMNWCFVDVF
    SOJPXLNTMYCPKJZYLEUO
    MPRMYRFIHB
    APJHPOFMCXZDDIXSKEBATKLPOGCYINBOOFNATAJC
    QBKZUFGLJQPNXUBYHXTQ
    GWZWPLSYPVOSIJMIGHDA
    TSSORKKMEBMGABCGKAFP
    BIHSUWLPCVDUYHIXTWBF
    BIURDTIDRFGWSYJKHMBK
    KQSYJDAGAFNDDMLLAIIE
    SFLEXAMOZUQWWLWYPLIB
    NTWUDBJJMOYQBNMBVTVFSIMVWEEUZGYAELXQJAOW
    RKEXWDBKYILJKCMCZEKAYNEORZONWXOCEISQFNWLSTMLXVGUFY
    PWTMTKUYSETFGUZNYIZQ
    GDOTGTHGCI
    RXNKACHLIZ
    NUGQWBYEXOZEANQGTRGI
    FFGCWCAAFJFURECRDQPCNNATISSYISZUXYVTAPBA
    YHJHYKCKQTEGXOIAIACBOXNLKKCLMS
    BDRCXGVGCBTGEOAJYQDHBMUVBUDUUL
    XGNJDQNDEZRWLJMBLXCBNZESSCBAHH
    BQGZGCGGFCGBDDDIBKFYXQMQUFNFGF
    QIOIDVPOKKWRVBCCYCCVVELCGBMSBMIKFOGJJHGYOEOENSTKNPIBTYUOINBJ
    AMFVODGCNJ
    QMHCEJBVDL
    BSVOYZSNPLERYJTJXDTJXCQNYWAGWZVNAGBQSQHF
    THHVNOQJKWDHFBIYWVFKVMQHNEVXYH
    YFOPUJSHFTMGADMDONSQVWCEOBIRGGJEJLFCMSAY
    PNJZIISPGQTBUATLPWBGKHGRUNATLVMUHXEZUMCE
    FHOEWNKSUZLHPOIGBMQJEZEASTGCMRUIANWXFVNZAEROUOWMAR
    ZBLEALYGZIDYCDRHAIMWLCMJVPBTDGJBNPQWUPPXROXEWONGTOSQBGZSHRRH
    GPEKTQUHVWUKXIAWTFYMPJWIHJBFSUUEKYAGYRXJLWDNWREWDJWCUPXRQLJV
    SYJUDGYIUY
    ZMUFXQOYJEIRLWCINJKI
    VFEITPDFUF
    NSKSPGHJIUBSIFAMOBZSFHVOZLJMYLDNULJFEXLRPOJUYGOEFLUBLWLVQEJX
    WOWWOWWOWWOWWOWWOWWOWWOWWOWWOWO
    GZEZHEZKUTZKWMXUGFRK
    OHNNZQQTFROBOLIFLJLMCKBNMBAYJC
    JNUNEOSPQV
    YKPXAZNSYAIJIWZQZNRLZYGYQIREOFIIQOBIXHGHKJTNDGACWG
    PCUFLIXHOWAFTQSKMHJSDFCTBJRAWLDWRMBZBPQUCLWGKHRAPG
    GOYMMXCEKZDEEESVDNJPXBNCPKIGUC
    TBOBIXLHTEJVHVQMNMLH
    CUHLYKBXGFBOCSOTRSZETSBLGUEAGV
    ZPRSRGIYTTFHLXVIQDAU
    LHCJDJJYRKKXGLZHJFDPGGYPQXGZRS
    WWKYWAYASBUQTSXPYPFBSDTQRFTKLJ
    OJRFMOCPTYUIITWNISZFQXLYLEVTCYNYIAFMVPWRYRUTCSYYBZFRQCUAYPYN
    AMEVSOCKKI
    FUDHFMXUNAXEXKDWNQCVRFWXOEWOWJCOAJBBSGIDTFMRULPTADFNCVZMCHNT
    RYVWXPFIPKNQZNURHIRPTAEJGXQSUDEKVWBBSHHJ
    QPCBBOSUXZUDIFBZEBDLOLDBNSONBKTFABBGOFRKQDREABYDFMATRSHOLWBJ
    NNQHJCDVFYEFIRJFKLRL
    LCPZSCWCABKQRTISDFWMQDVXJIYAQXIDGIHWXZFBUWBQZWLDQR
    JZQNPRNQJP
    BJJLUCQGWADPUYANVITJUTMRIVNPHRZRXKSVKQBI
    HVQQZQWHFYFSTBSJGFOCLZNXTRQIDFKOUZGARJIX
    TGZDHVKSCVAEALCLQWXNXAIIAIFDLCPSEBAKSQSSTZYSTSULAO
    MDFIUUGZSYZUWPDVBAPERQKNGWCWCV
    TEVEYOANBWGLWWGILDJR
    AIBPWWMWOIDNIAFRSBIDHYJTVCYIMGNCRKJIBYDG
    VPPMFYIHPABBQWEHXAFCNSPYZXDUKYHVROKKSLNSBQIGGNPXTF
    AZIEDJZBGWSMLZCDXUUXMJJOMLMICMLFIVTNYWPEGLILSFXMRDTQVRZVODDW
    YNGCBODGUMULUUOAODVA
    VLJWVLVNHJHOSMKYRYNFLUSQPKMYMXDREVWODJQLCCYUEGFYRFFPQLFPRUTG
    FBFCADEMSBMQWYXHZIXFRXSLNPIPTA
    VVAKYABHVH
    KQDVWOUDXVFVAMXVNUCS
    XWSYEQGKIZKQEIWVJWDTKGJLKRWMZJZPCMSCSFNX
    NHZIMZOCXFSSRXHWPUIJBVUIQHPEAKGDRYGRXLWWORXCGCJGUVWIFXKJPJRQ
    LQZEHDXPHHJLTDXCBBFFMCCQGLSUCYTCNLTYIRLFPUORCCKYAUYREOVZQSLB
    CHIBJUTFSX
    FIBOKZLMGFEBROYBBKDWMUYWNJQYUPBAQXJHKSBDEPWHSKHZFY
    TMIKZMUIXLVGHATZNKGCFAHIIZDKWCVUWNDXCIAOZQPKUILRCLWFMBQEKONG
    PHLIIVAZQBRAVJTIYRIGHXTKLYGGNGGKYSIESYBQKPCBNZWYKLGYWNPTFQOK
    SJKJQYDDMOXWOHNNQYSK
    ZPUVTTOUBAUYWWLDYHBHFKYIIZPZIMUICYXEAKMMIMVLBQLISI
    GGRWVCFRGQLLRINJIFLANZCYIFDAGITJZWYCWMVU
    VOSQRHUXPJYTJGZYJQUJ
    CDFHNGGQBFBTCTBTZNYTIVIFXAUZHAVBFVYAVLBHPUPRQTNMVN
    QKKZBOXTAHRCRXSBULYHPDJJCITWFU
    FOPVFXZGHD
    WYLWXLYRLRTMWBONLGWKZWWUTDGRSGMLGHDTLAQLFSETWHPUCN
    RBCEVYQTEUHQAHEKSNBY
    YBCEDYIZFIEEUDDNDNTLXWHUWHIXJKHMFLYVYOHN
    VYORVSXETGUTLEHZRAHRIJFOTUILOIEVLVLUDXFMXYUIUDQSHR
    LRTYQRHWJFWSTSWPNGNRLGYVLZIXYTBBLPUHVBAUOFBASCEWVO
    XFDDCFHCTQGMHCUITJNGLOPDHGLMGENOWKZRTXSLPXSHBQNTCAYFMNQNGLDB
    HTQBPWQJCK
    EZDMCWVDQA
    FKMYRSKXYMYTCAESWTYRQSTDFGJJDCZMBJBSCFXK
    VQHDLMODEDFNYGFASWAECGSERPVPGWEKYKUVUTCCXSFUZTVUWV
    ZRJHDXNHYXKZIIFZXSIDMTAXEFJTNYKZNTJHMBBYFDZSIPDTJE
    WGYPYJBURXPXLKBVWDEFCBFDJKJOQNGHYJVARUWMYQFBMLTKAO
    XPJERBOIHP
    ENHPMYBUJC
    IKKVLPXZWWKZKEQJUMQMYGFTZSDIMEDNBLSQKOUA
    BAZSFZPRCIIFHRPYHMVYCQMZBCUIXE
    KGIJVZGCQYPCRJKDPOQV
    BBGICVMHPVGRWODHOHDWBTVRPVKGKIDLNNPCTGJVXBUPTTRBQPCETIGOALAM
    AROYKUKGXNIEYSYPKMQNCKPXJRTAWSFYYRZQRIHXEDMMDCNAVT
    UMZDOWQQZNGVWOUJDFQZIFQHZDYKPBSKTGKZMGMZOMTPYCASIF
    GOVPPIXJNMVXRLTAIJHJXBQCPWWRAQMXSTJGLGQXQASZXLMEBK
    PYDCRTBZXHRKSDFMWVZQBRMANUZRSYANLELWRTKNGUMFPMTYVT
    YXEIMQVQVTPHNVUHARIAWYCMPNWZWUFXQDYSFHCC
    QISWAQDCMCQEHWPQDQTAPHXEAVLIIKDWNGCXJQDTLVDYXVJKEV
    NTAJMMKFEDFJRALCZBHZCNXBNUUTTWEOWPDTBURMOUXOXSXMUM
    OGVATYGAEIXMBYSZBUSFCFBFZNMBVW
    UAXCTPQRGZZBQLMZNGEQFOQEFSXBHMLJNXRRVPYGUXIBZJKBIV
    EBKTTMDOPRWUFCEHHISXKVCUIHQBMBLVXHAMVXZL
    CQSZCJNZVY
    BBLOXLPGNDQMWBOUPEGPDBRBBMMDQUUBAFNGCFEIGFKWHMQPTKQZQZSSZVFZ
    BFBXBTERIM
    CYNBMYSHJDYYKAFHTHIS
    UJLMRKQFHJELSYBXAIXCCWWAAHGRLFTDMDFIPZTL
    MWGSQLXBEJUJZVFXJYYONPUINOXTXHRRLCCMMFIAMIZZTARGZB
    EVHBNVRYFLIYQBPZYQGLXRYVGQJKAF
    WLWWYPZYEPQEWAZZBVIFNFDZLLYSNO
    SSIKJTKZVDYWBBMNSGLRUABRXJBHBK
    GKTLNCVGDPEGGENSICKZPYPETVGMWHSUBYBFGNXYPWDNTPWFTZ
    PIRXMOXWPGMRPDROGAKY
    IKXKRZXBSSBPAYRFLOXKTDZTAXJVUQWHDIEIWSFQJRNRYIPURR
    GKIHJWRTGLSRCXIPRLKJYBZOYYEWOHYJOUTIWZEQPGMCQFHGGUKVZXLWUTQP
    ZEFGNJPNXYEFVLUBUUHTZNRZEBRTTFGOEAFEAQIHVZDBXCZFRQ
    CIJWWLHHFGMHMMHSZNWIDJRXTOAFMW
    FOSQZEOEQBNLEHKKNRSMNLIQDEYSGMBSBFZPOPXZBMAYEMEVWP
    BDCWEARQKOJIVIXGNOKP
    GKAQRPHIKAGYWSDJSINN
    JYOCZEUNCGILWKNIQUHBPEREFKDNFU
    IAWAJYYZETGHKKWZBPYZFCQNCVHGDXRPLPPCLKOQCKNPYIRIPURDMRYQLQPD
    PUKRNSYWRYZPAJYJUXLNKCCJAIDKEHADSPMZRBRU
    IGVUDADKRKXKIMLMNWBH
    FPUFFHWWJYCMYTTAGCYFCYZOJNGOAPTFWBOHHLOZ
    HWXHDOSGBZDGHQHACVYXZIWKDJDQWCHJGBFDNNWAQHUFICQITC
    IEHERQDKAJ
    KFMVTDOJZS
    RZASTQNUNUZXNNTFFXIW
    YVGVVXMNHUNGMLLNISCYMIACPZSVKWTPCDJLVLKWOTBNSIKIYAMBBARXFSQU
    ITTWPJLXNLZRXMCVXHVXMFBXROZUVUMQBYVOUNKUBOPLSYCYXIPGXFPEQLOL
    IDNJGCLSCRDQUXAUYNDZCOWZEAUWSQBDSLVVNHBVHDIURJHKMV
    RIHCBMADMF
    XPWKTXZURSKIBKTSMNPC
    EHQPOKTHSBVYOZNDYHSE
    KXNWXBFMQJQDPDURTRXCMUVHADYUNLIDYAZCAIBVLDVQKEVXEN
    LHDVMNJRPREPTJNIXCLDIWGLIBMKIDAQUBZGEERF
    FXEWAWRXMJXZDEYNNIFI
    EGUBKUSWKQKEIZQNGCJWAOHZHNGQMNQWSWKETQZDMEIHBXVMQFXLEJMAAOMR
    NWPZORPZRYULSNLRFDDDCLMKDMIYEL
    GBNADURUZEINRIQHYWCQLJXZNNFECHESHCYODUPE
    MRDGXBTOTU
    DLLPXRSXQKLGJWBDVCWFLMRLRMGHAHTJVRDPIDMFPBRCHWWMUNGGEDZPBZID
    EDIIVDAUVDBCQZXUNTAUZTNGHVCGLOAEUACYLWQVBDBPBWGXUWAHAWOKWCOH
    PQWGBGVALJDCAWSQOQCGNLQEGGBMJPBLFAQPNBLT
    RDHJPKBFCQNKKPTVCLARFOENXCBFIE
    TNDMFHBLRHUDFOPEAQCA
    SCZLGDZHPH
    IYBMVKUHLEGHXUEMDDZU
    YNEPQXIAPF
    CVPSNVMYUYHADFCRWDKZ
    KYSHCCIBHCBVFNACATLZHHFQUQNZEYOKYLMIWHDF
    UEUZCDVCPHFOOOTZHSXRLIAOJEJORNVVRJGOEQPBOGYIMGGEQL
    YREQKANYHO
    PYQHVFTNXP
    QDISMTYIPLFZIOVFTRHSEMZIYZNXCR
    MPLMJVGSFUMKKMBMLGVYATDJBLKPCCIYQBLBBKND
    MOZAVQROXSSRYFMANXQVARBHUIWCPZOHZVJMIZJR
    OWMFSSSFQQBZRXGMMJJDJZRLQVAGMEMNPFWJSOML
    LIHLQVMAKHIISZMQYXOAZLAERZTEXE
    MWLJQBTVUTQSXDCALFUKZAOUAQJYVS
    CQKBDMZWCM
    OTVUWOLDHWBTUGPSTWZIAGZCIHORMGMSOMKMUHSQMCZEIUDOGFRKMGTECSNL
    ZLXAESVKSDYZFPKAQANTMWZDJPWFIU
    VNINZOISCR
    QQROUTBOZLGGKXVBZKRCHOKBSWMUWM
    PLVWZLFECAFINUGVQQBQ
    IQDBKUHXITXKTBXGEKTHWISHNGDWAKMEPYMBDXDM
    ZRZCRQMIWFCJNMZCAOUFMZQDQJFZRA
    VPMTYETNRL
    RYWNBBTEKPXLOVWXFZWFYAXOLIMPPEMWUHBVMEWWHHKFAMDFEY
    MNQRWVSOWMOMLGBGWIQSEKSNJSEKTDGEYHYPXPOU
    JQVXVUETSHVFGJQABTIJCHJHZRFNOMHPZTTACVIR
    RJLWFQIKZAQYDGDKFKNODJZWFXFNAXIOMOOAYKQK
    OVUFQGFDFJ
    WYSQFCKKSV
    TPJHYJDDVBIRITJZLTCIFYDBRAHIOCIMBQPUWUVA
    NQJSCLICGFPODAPWEKKVOFLFCGDNSKFBTIKBVLPTKMZKYBOIRFCBZOVRIJUI
    FIJROOEVKRYUGWNQZDTIJFJGKJKWGLBOLEDOTYURDORZQZHNTE
    BDXEWDKINV
    DEFGMQFXQZIBUIGDWZXKJZLUGPGXUBACCTYVCPTZUNZZUUVDJRVSFLMCCSNW
    UMVTQLNXLAXTNTIPSUUSBQZQAYHBQV
    ITEURAAKLJCYXTYLWTPPGWIDXWSQCZODZPPJAFOG
    MVFUSNBKCAYGPJHDSZLXYLKFKHCMFAQZXCKVLCKQKEXJYWTZTMTZMJKHLFIN
    RJEJQGDQEQMTWPBCSUJCTNPWBWODOP
    YROVVSFMTNKFATMOXBCH
    XFZEIWPZMUDZWSZHCZMUQLOPXVDXNTBWIZVYRXNXQHTGMFTLQB
    BXGDMDOVWBFLRCIYPONVRKJSVRLMTNSTTJPRHJXLGPMPZYFNEH
    VGSYXGVOTCJKHCIJGCML
    DUBXITMOPZSVRMZWVSRB
    HFUUMWGYJPZPHUJDDCLAHDKABKHVLCHYOUUUYMZTETOIGRGJNO
    KGCLNCRNUZ
    QMLKBUCINNRFHNHYBUDQGMAMJOVRUJAJFPLGCFNV
    HWUCFKCPBBYVQXOJIPET
    JRUONXMJESNHFCFCLBBPLAVQHQLBTL
    YDTHCGAAKCKNNPIHNEPU
    FZULAWVQSXBMYATSQHPRIYYHEGEWMPWOWHCANGKENSZIKFWPZM
    ETIVNWFTEMSOGXEMBMLJWOLHBMARVXBLUTGPQLYKXZVQWPGZQAXMBPXTYXCI
    RZOISPLPYKCFOXUDCGLYJQWHAGPTMYHFHKRQTFIYPGKGIEWHLVGUQWJHMOLS
    BMSVGXFXJWQSSRXTYDTOGPVWIEKUXQGRXYHZFHYCQWJGGGAPRF
    FQLJLOTYLLOKEDISPWYA
    CGIBWJHXNG
    DFTFXCSWSRCQPMHSVOADOWXWJMZZHQNCPVIYLLSN
    NYWNAIKQQHSBKOKUXVNXRYRIXDFLZJTOWTFHWWVN
    ABTGPYUYJDUOTXUAKIZLJJWJSROMPXYHPYJQPKGG
    FXUOSPWPGVYBCXHJEFBDGRTSGYFBBRIBALWDCMGTPTCYRUDXICBBMOALTRQB
    NAWMAWBQGOQLRHYIJEOLJFTNUKQMPHRBFWMGTOVLJRTPKSYDTT
    ALZUYMPGGOKITSRVUEJEODHQELMHWN
    MDFDITXDQUZSAYHVCQXPZIDMWIAAELEPTBXUTGHJ
    GKZZGGGABRDWNUPKVTHMEIIYOVNNQG
    XELZNADYQY
    SPMDDFZONGOJWNANSZVA
    BEXHYXJAHEBHTWOGJCYHXDYQTFOBBPJQPACDGTNYSIRZKEKSNLMZTWRSJYFF
    OHEBHIVNIWJWKQWAXROSCYIHWHEQOVMCXDTNQQNB
    BAAQWEBFOQNYUGFNILXP
    IKNJEWJJGR
    TMUVARLKNCSWQCDNCLTSHOHCDQKWDVJFSLYPDYCEJCMXSHMDFQ
    VJRUHTDGGDVSMOEXRKNPXOVJVLAQLKPXGONTIZIUEYBCJHMFEKGDTYWGPODU
    DTHRLBWCORMEYSZCNJXYTHCHPDIPSBZYYPCLVVTI
    VSMPUBYKOKSQZQGOJSQPILIRBVNGKFOAHFVGDOUQTGSZXKAIVL
    IFYZQGZCNGMJBJZBVORWDKGIGXBWUXRGCYRLGTXF
    MUJKSYQRSE
    GDBLYTHCNEXTCJOBBZFJTVEILOOLBUMLMTBAWEKF
    TRKGUJLRQEKQNBPISVNR
    LVOKONXORS
    DPHYJKRAPIWECTVOWRMXBPAQUAWLGWLOTRKVZXDI
    RHPKETPCDNJQZWCABVHM
    RYEPJQUETZ
    JVYDNVIDXABYKTHLBBNWOXHHKOCMBIKYKICMFWHGJLNSBRWFHVKWUMGOKBCY
    LCSSEVFKMBOAHAQEULRAPORSKXYLUCSWJAJKWDQA
    XMHGCTBLFBFLGXHRTWWIQOSMGZOTKOBNLHLPRWXRZMDACSBVHG
    WGEYRECKZY
    CJTPJAPCGPIAURULOUWSRLFJNZTLWTEQGQBLGJZUNUVESIWDEARQPFLCZTFB
    YQGAQMSUDS
    IJONDFOMZUJSFSZPQTQOEVFSFPCDKEDPGVHFNYIPDGPYUUFTOK
    BOPUUQEXCX
    CWPWIHCUJBUXYBXUYQCP
    WOQBFSENIWXRNQFWYHWXTUYZNCTJTCTMHJBIDKEJ
    UGMLHFFINILMOBSENODR
    GQXWWOJTFZVBQAPSZQHS
    DLQOVGKRWRMGGESZKIRJONYDPVWIZXHLOZIWUKGQ
    PBJPJBGKUB
    WVYDGELNNF
    GHVSXCBHDE
    ZQQMYBRCVQISOMITYJLF
    JJAFMJEPKB
    AGLLHWIZLWSNXVVTTIEUNEPFSOSLMW
    LXJDLUOFKYQTBOVBLZENDGDVEEFSZNPIFWJPWMOB
    HQBZJNHQSKLUYPCBIBPTQAZZFUCYBQ
    BUCGNDKGFYVOZTFQDLUFGKLEYZYXUV
    PIIODSGCQLZSHOVWXEIZKKWEQSUNFL
    NEVCRACWLI
    QOYJHYCLJBLEGWXWHIGXUFOEAIGZIDZZWGGABJOOXAUMJAAVTSLDHOXNGNKL
    LYKMHDAAVHUTZVTIHRGHRFDIGOQOPLRIWCNUKZUHAUSKNCJIMORVYJRBDWYE
    MLNBCDCXWYJWZSSRLFCAALVDBGIAGISVFZVZGRRVVOMFNMHZXN
    FVEIVPMOLPQHNROBXUPRQDNOGNWBLBSCHMYOMPLAGQXBKWMYGY
    UVGNWOIKUCFGNHRJJEMKRTZVVVZWDJXBPIFYZSBU
    RVLNFCYWDQTHNTIXUAIXTBZESCSYEW
    MITXCKIKYMNNPENMQNYBNDRRMRZYCBSSUNNDTFNS
    FMBMTVILQPJOTYCPLIKMCJBMIMHNWGROHIWEPJBPBNWRQLKARV
    HGQMEUEKRESLOAUUZOFBYSIQJDTBVJNRXFNEKKAV
    BUKOPBSRQHGQEISVKEJUFQQCLUFVNJUOVKCQWDVNSXJUHPGTTU
    WBHENSDHBBATEVEZDAJNNKTRADHFYEIZJCGMIBHK
    XJICTUHUAYMVOSHMJNILODBANLPUXZULMETZCUGCDGEGDFLISTWSDHWPIWTE
    BZAJOJTXFOBJQNASNEGKOADWJAVJBMLEOFUWFEMHAESXADHMVR
    PUBOAFEFNWKWNTFPURWLDFDIHDSNTC
    MEZALBGROJHNGSQUFZWF
    WBLBIVFEKD
    RYFAWFSHGFUUQVFXZQSUFMFLZEDBVQYNYYGVKIXEEAAQPSILCWHCRPSLFNVI
    JKALKQTVGE
    AUKFIVJWBTIRBZAWNWXVHHSOUCFEGM
    XOIMHEFBSMFWDCSIDMHKPFLCMOMGBWRJVPCRFQBB
    QGEALGPGBE
    JKNSFRLEKXLFMPORVEKGADODSCPCKD
    YIKLDLWDHEZDWEVMWQRS
    SGZMUMKCJUFPPJJNISCNTAUXYBEGFS
    CICJVIEMTPKYUPYRBYTGWOUSWNQZXPLKWZQCFOHUVHNSOSGPZJENLTYKGLLV
    VEOARUOGMRLXWJLSWERO
    JVOXCBMQPG
    KUHLXDPXUQIGDWTXLPOSMAJDCBKCOFYLESTBDDDY
    DFMNITXHVBWVXBKHAGTIFWJJDBMSLEQHRIRMOJDDVAHISMOASEDOOXJBUFFP
    GUGZMZRIMOTOUDSYOICFAFPENKSXMWUUDBJGZELX
    CZPWESNXVXHPVFGNTDEDPCVCIWBXCMHVUSYTFZHWBVZRPVHZWMJEQXGZTKDT
    BPKABXHGECUKHLPKGKTJOTCQIQCADXVRQRPSVTKEDQROUENVWT
    IHEGKCNOHGMETCGRWLXKSBHJCPYQCJ
    BBMFFVKJNHNHWRKUIVMMSKYRRJYORPYDDZDNXYUSSQURFPDRDPPMTNNFDMNE
    FEVYUBYUNRZGDNCYVPRZIMGAWDYJVETWZCEOLQZKWHFINXFYZIGTKLTFIEKA
    NGJXQQVMBUERVXTZOUUCTEIOELBYRVWPZTFNWYOGDAJDEANCKF
    XAJBLSCEXELMZGRKDZKGARGOQVIBMFVKEKNJDIOHFWXGCSQDFOHLQJFMUQSV
    TTOUYNEUPIJFTSXVZIFP
    TRNGVNQZVXCIVVPLIPWZKORZMTYAXYUOIANOPZMR
    HVAQCBVSTIVXQDZUADHWTNZDSZVEQCEUGBBVBHYBMZUVZZYQWD
    YLLUWZBDIXYNSIAITFHK
    JJOYUDNDRNNCRLAEEZFMEFJGZSKGKCUHOVOYGIPNPSLBFEAAORPSUOMPECJH
    XVXEFHAIBTXHZYIKEVAGHAUSRRWDUD
    IRGYGSMXGS
    KNAKVRXPBKFBYVJABZITAJESMSOAJEZLDCZZBFUVPCJMVYTVJTKNYHYTTYOF
    BUTMILQKHPTNYBYSVLYBTHCBXOKFTXSPKYRJLOJAPVCSSJKSWV
    OLXAXCFPBIEMSZHERYDY
    CSVCUTPIKGIFNZVWOYTBSKAQRAZGEWRICPLAVHDCBHRLWAKUFCQEMJFLPJIB
    LSHLTOUSVZ
    SQSMFIMUTIWSTCOLELKOCESHAIKHIGSLJECVZZJC
    FTQCZQBYDGDKTXYKEBDZXZIZFKPINWVWYUNLFZWCEQIHIQODTHVHXUVWSNLP
    JFWQGJJEFZCZQIVXPXTXGKTEWEYQAASJQYMLVFYCLDTOVODZVS
    RWENWBDNOJBZJCTTIVBAENUMBMFJGGYMPYNLNWORVYXGPADEDBUDLAHJWNKT
    CHABLWVEVW
    YYYVKLMJUOKMYUHGHKHG
    TTIACMAIJAXUDDVXYAYABQOBPKLKEPEYXZAACDUSTPAEDYHIUC
    GJPIMIZBURHWQBKOTJQPDPMJMWZFOL
    FCXZAGFWIHZWIZKDZDBRAVCXTONJXIHKKNZWCJOB
    LTZBMDIHZEZLYZFYFKGCWZGEMKUCVDWEYKJBRFWI
    CUYJSJZARJGGQFAWQEBBGSPTJJVKQL
    GGQHVRWGOPNECKFRTERBGFXYPYYXLZQAXIMFCRKETAOBFYPSIVWXLAQOZIFL
    NSWVXIWQIARZIWUTDZMTNKVGTDVDYYWCXTTICEKCVQYZNMWYLP
    WTBHJKMUBLIPEOZEKGDJJACQJMRIMI
    DRIVTOHFAFYCSAGBSDAMZYYGUFUEWBWMQGLAXHGWUQQHNUXUKMEPVJUCOOSA
    NGBGDBOPASXCYBZKZGVI
    ZTPZPINETQWOTBKGNZUA
    RICDDRMOXBJHRASVJLEXTFHWXWAVZMWIATQXQXPPAXSNWYDHTJIUZEEBXKEF
    CKXQYHCACWJLOHWQVBGHYWKBEATWAHHFPYNBYYYVHQYPIGFEPZ
    VULNSQJSWVQQZRJDPUZOBGPMCDNYYOHQPHZRBPQP
    GQRMDAQCBPKHSCDDZRWJZOHGLMEGYVNQOQYBTABYYDDSAKYYOP
    KXWMXHJNUCPCGZQIQBAGGQLXNKUFMUTXHWXGKHASHPEJWMZVBU
    TVIZSYUWDT
    CJTWBTZOUVYNXDUREXBNAFHFFMTORJGWTNAHERMFKOKZQQHWCB
    AOYXDXGFIXSWPQVJMKWBOTEWFUXWRL
    KSGFFAVMUONCARQJBBNJTYOPXSRDAWWXSAINJUQT
    YHYQDSLHER
    SUFCGAEOGSYXONPGFCHFGQTSJWBIDDFCOOIDMDJAWHHSPXELTE
    VZWSGYWJAUKGNHPGKEVTMMRHXGSAUHJDEEEMQUWH
    FRLVZBFOMWZKXYTCESNQSENIOLKUOJEOYJHAIAHCPELJIMBRQONXUBKLDJFF
    CYKRTGSZZRWPUFXFMLFTCXBCPCDGLLGFYCGSVHYWEXMDOYXLYVRCKCGZDTQN
    HXCGJBUKIQVVRPEZJVZQZEOGGUKQDQIXZFFEWFXG
    VXPHVPIPPGSNUVGHSRFWZQQIDWMYXK
    HXKJJWGCUGQPRFZNHMJVCGJBOKLWAMAKSPPENTYHTANLXACXZDKEWFBQCOVS
    IYERVHPFIIPRHZBLOMNMXYOHRIKJDJ
    SADRYHGNYOFEJMDXAZEM
    UDFIOFUURAZPEPFHPUTMXTBLUGZWIBDDFKFEBCXI
    GFOBTFQMAVAONXYAISVY
    PPUITDJQZLOTQXJZKSCMWFTKSYGNDHJJBXPDTYAWYMWUQILUSSSYVIIZQOES
    DFXRWOYBPIINELIQKRJT
    AUHLPMRHZQLLBJXVBKNGYGPVRLREANGDCRGRBHMHLYGVNJINOW
    VCAHCAGOKSRPZJGKTYRAHHSHCDQPFD
    SQJZAKZCWXHTTHXAVGPFRCBCAMIRTXAERPMMKVGGXLGQJZPYBM
    UVVGVUUTICSQTABGAXJKRPPIRPNFWICGFOKQIYYOSHNJWPEMTR
    ZPLPYDITQGDKZMMONCMI
    HCNVPYUJVQEEAWRULOMTKKKPGNXYLMPPEPUJDSQCPKVDFGIWTUVUMILYSVUR
    CTFYEWBZPLVZCMJMITFGBZAQOIGYLCHBUJODIUEXHAOGQCRYCB
    QOJCRLYZDJIOWZSSHZOMMIHGDWJPWGKMARISWDRLXBXMQMAHTV
    LFVKJOAHHBMGTLBPPMWGYKPVFVVOACKLFKWGYGLGWGOKJYKXNJEXVEDVMZWT
    DMIXCJYTYUJTSBWFKZLAWKPHURQVOYDWETNBVLJP
    FOBECDMQUOZXAKOVURYSWQALSYQAODWYODRTRTRLMXGPCIGDZJCNVHMDFQVP
    KKMKWBZMXE
    ERFHTAWFYLEMXTOLACJEAVROLPBFUX
    DCCRBIXMTBGWGDDZFCVXHYBEVBYNKO
    RDHWEPSVEJGFKOLVBTHZKXPZGKQYZRKSNZVEBEAM
    CHAPYNTKFGTYPMFRIEPO
    YDLWYENWVBWSDNIKZODIKQQCXTOCSOVWFQBBQNSFFYAKRYHVJAOKNTMKLIQP
    DQKMWSPFOLHDUJLXBHMCAJYTXCTXQL
    GSAZVMSNXJNTJMZOZEMZBJCKSXBZMWHZMJGDMTHF
    VNUDTISUTEBRVRMTVVYC
    KWUNMCBOUB
    GQYIQAUPUWHHRKRREXOPBDEEKKBDSAGNSYJUOSVHLWLVBVXJAZFOSJTUHJHL
    HRVVHUYOHKPCAGSFSPFN
    EYGXWXWNTQ
    BCNAYQBQNJDYOGOPJCDMIJWIFKIKXLZCKVLRFYULAYEMKCZTKJZBCJCZOWID
    TVHTXQTVIISFWZFOQFBV
    TASOEUUUZR
    AFHFQINSACHERZDGGJGDXPADUNSHIZATVXTZPGTOZNZAOAUWCK
    INLZDSQKAN
    VSBIFUFDNHODSOVQXUZHBHNOMVNIQRMDNBCPVMRPUVKNVVNOZV
    VASAFULTOTGYSDXFXSTEJJWUCWKJWE
    SSAOSOOEDD
    PELGCIFVIB
    MRIWCFWENRTMPNHJOBUJ
    EGTCRRNWTEPIJNOHQDFPIYCAVLJJGG
    AVVREYHHQVZHSFZNXSTMQNLUYJVFATOJJDYJACSHYJEDOURHQIXDBCDEBHDO
    OKRRWKDUOPNKVDJSXFDG
    JXDDQTIFVIPPRGNVLNCOJRIDHRTJTWXPYIOKCLGLYUFLBYDYZMKJDLVQLZMM
    XQJPWQQIGEURRVTVQXJGHRPRFYNGHYSXCNKNPHXDLOAKFSAPTG
    YXZQTNMOXBUVLOLEDPYQQFYKPUTKPK
    TBLRONSOAVLCFUYKILYHRBUDNZCVDC
    QGVRBJCZTBWUCUCRIMSR
    LWQJURTJXZYVBXNIUPLTFFOYXTZCYBWTDOWPMYNXPYAVLNNSJDJGKGBDXKJE
    MVHDCFRFMIGUITXJPSXIEBHSXKERBE
    VBRPNJDGNJCWTUSYTNTAYHWNKPLEPDPEABIKGLBZCRTWIYOQHL
    RWFZCGFDGUVYIQYRHBOO
    QCIKVVEMVE
    YTIOKRIXGSRWLSZTJTBPLZUZWJBNHP
    SAKPATNVKNFSSVZIFWIZLSLYODDDWS
    LYFVAJJFVKQUFGAGRZDNNMUYWHXBDCPEBZJTVAORKBVQXFOMJC
    QCJJVEYDTMJOPIRXNHUGNPJNIHIDJO
    FJIQHYMXPDZFPNGCGOXFXJKIGLQHZKUOJVJKRURE
    DRUBNPGLFZMDUHUWGWLEVGPKKTOTUH
    KULQUFZJKDVYWDIFJUWPHGTQWTYGSDOSRONJFWPFPWWWLLBLKVKWMLXBSWDN
    DTSUNDHSLBWJZGMJUDZSFMFNYWAQRKVVAUHCOPXYYPUADPYRGBWDMDNLZNSO
    YDKHSQBHBWDPYRWSOYCWDGGPYJKWHYGJFMVXVWPSCWQPJNUDLSPREAESFBGS
    VKABDCCHYAVQWWZRDGQKVBXZWVYLQD
    UYYJODHBOCDNPNAAJMOYLYKHSKLXSO
    AMGWATERJEGHLEWQCWJPZRUZGPQINZNMPMUXMANQPZVRLAGGCX
    HSPAEPXZHSEIJAJBZOJCVYUBPZLYZNNSEISMYKMFQNFATDMOTY
    GFPFZYFPZNJQULTWDYETAOBPEACHWBXIGRAKEZTCCCCQFDIHOIEWGHCVPZZU
    NYGTNLTYNQ
    HMMULRSOAIZCVBLBJOYSRZIVLPYKPN
    MIGRUCBFSTSBUMPRXTQIQKYDYVUTPDRVOKNSHRCOPQYJTHBPCOULJLRYCJJY
    IVQBYVXTRKBNUDYXNVWBJPNPXTZFTBAPWGWIBODDQFZDDZPEUKPJVUPDTOSN
    RFHDAAZZATIPGQNUDNMFOTLBGTBOUDXHPPESBUVZHTKONUGQMZ
    ZNVSXZZMUHOEKSWXUEICIVWHQFIPCV
    KACDZXHYTDKOMZHVMYWM
    JNMQLWPTSY
    TKHHTWOFUTUBYZJXRODFTMZTVJTDCCKRGHCRLYACAHPUMFOGRA
    IXULTLRRICUKELYDDZEQWUSJCCPDHNTUQVVZJJDM
    FOIBGJNUGUVKRCACFJASPGZLRZNRAZ
    GSXIGMWXCMZIKZSKOVLUVXUNYVPCQW
    UCWKRQTBFDTESOFGOUBP
    CBWMLCCLUFWJDFDRUOVF
    JRWPYONENEQECZSRDAXC
    PSOJBUVKCWQQWRUTZOXCPIJWCFDWWAKQBQWXLUFPMOQKUTZNGPJYXGIJNAYC
    TLVAMVMBGPFLSLWNGIDIBSDUEPDSDBUWSWJRNMZR
    OZLTJCPSPIMLHLTYHVXYJONZCCXPBACTFFTDUCQXRQTQPMQRDF
    EBSKWSLAPZZMCNFNZNQKOFPCQPNKQN
    OJPWICAOMCIFRESJUPRG
    JTXQMFXCZLRILJVFOOCCCHOSCCJMLSEMIRZICOXJUKSWJSBOFB
    KBIHIAAQAAEQMCPPCYQL
    DGXUOLCJBJQEXYACTPALLEAVFCGHRLWLDLWWOUIN
    YQNQAXUJAM
    JZGDEBMQRJWAPUDAEZTWUZKVBMBLRNIVZJJTUYFHFHDTRIFPDQ
    GGDNESDCUWLFWDIGXGTCOSRLKPUDSFZYMVQOBJDJSJMYCQXZFT
    WERTYOOOOOCBZXCJHDKGVCYUIQWTC
    FFFRZIRWIUFEHCOROCFFGOLBLWQLMTNSVXQFMPWY
    IFDWBCGRNJUVHMJUACMKQZLYQWTWXQEIBGQDLFKR
    PAICNUGXYJ
    XHMTAJUAGWMMLSVKWKHVPTMGMXVIXIYCAJDNWOBEAURBJHVGJBYSESUDVKQG
    BQCHZYPZQI
    CHUIJEKCOWYTPADODHLTPKNPQJKSZKOCHOTWFZEKMKRYKYRXPQ
    LJMPBISUNH
    BKELESCVQP
    ROCFWIHTLDTYTWJADTFDYGKNGVCSOYYCYHHBKNMWBFMHPZGBNFBNAWXTKARE
    IXIXCULNPUCHTWFVVXZOGYGXUYFGKL
    PXIMCNDJYFRZYEOGJHWFFLOXCTMWZOWXGKLXUFZVFUXVRAZHFIMAIOEIOASD
    FYBAYAOJQYUNPFSTDPUCPYGSROSCEWFDIQQMCPVWTNIWGQZQPT
    BJEAQMKAISDCPZQVNDCE
    OHTRQLNDTNMTHXTOYSKU
    GFKATFGXZVMZPKPKOLOEVIXCAWGPZTDZDPJVKHWPAGIRYRDKDUWVASWURBPD
    GORIKHJAFGUKZTSPNILFAKZAJSFQHCLQPBZKDLRAOEDRGQRMLD
    UWPKKIPJCV
    WTHMCCWARHMTYNGLZBRZKCXOPPLAXGYGEJABINDL
    YQYYESJZSNONDMSFSZXKEPGNFHKUNKWKQDHPPRPHUSYPHLLZVU
    YKWAEBPHLQTKFLXPWNGQYVGBYHOQNSYDHFPZXBNM
    ICEOVAMJEXSLALJLDIPPDBJVEOCROU
    MFYWYHRMBRTNUOFYWRUMSBTTOPQTAGSMZRCKSYEX
    SUJBNUCZILUYGQDOEQNURFSTGHBUTDDNDGKVCHPS
    CEIMWPMFQWLBJNBITLBOMSZITCMEJD
    PYIDCINRBU
    QQURHBVCXEVOTBNZYAZD
    YUOBOLOEJXKBLLHVHUHJMZERNYXSQKCZCLVGADJOBYNBWSNLBN
    INOMDOCYEEOWFHQJUSJORUAVXAWMNGKZPQBAOKJSVHLOYPFODZ
    GJMWTRTQYTVLHTVDMYUFRHHWYHGBCNOIMHRTVDKKRZRBQYIBTX
    UACGZGJMDK
    AHAUZTPTJC
    YYJNSAGJERPZWGEQOKSBFVIJHQXGVVYHZDCMDEXLUUVBZPKBXP
    RUPYJQVKJUONIQVNULNUSUTUCEZGTOBLHFNUIIRDDLWNESLWZAJAPUGWPMAE
    FYPCGYVWWALFIVWMDEPFLEBGKRYLKGNQZGKGNLJQ
    YBYLTDPRDKZSUBMUFUOSGZMIWTGSKK
    """
  end

  def part_two do
    # input = input2(:test)
    input = input2(:real)
    {words, phrases} = parse(input)
    words = words ++ Enum.map(words, &String.reverse/1)
    text = Enum.join(phrases, "     ")

    words
    |> Enum.map(fn w -> scan_word(w, byte_size(w), text, 0, []) end)
    |> :lists.flatten()
    |> Enum.sort()
    |> Enum.map(fn {i, len} -> i..(i + len)//1 end)
    |> Enum.reduce([], fn matched, acc -> insert(acc, matched) end)
    |> Enum.map(fn s..e//1 -> e - s end)
    |> Enum.sum()
  end

  defp scan_word(w, size, "", offset, acc) do
    acc
  end

  defp scan_word(w, size, text, offset, acc) do
    acc =
      case text do
        <<^w::binary, _::binary>> -> [{offset, size} | acc]
        _ -> acc
      end

    <<_::utf8, rest::binary>> = text

    scan_word(w, size, rest, offset + 1, acc)
  end

  defp insert([h | t], se) do
    if Range.disjoint?(h, se) do
      [h | insert(t, se)]
    else
      insert(t, merge_range(h, se))
    end

    # case check_overlap(h, se) do
    #   :discard -> [h | t]
    #   :none -> [h | insert(t, se)]
    #   {:replace, new} -> insert([h | t], new)
    # end
  end

  defp insert([], se), do: [se]

  defp merge_range(a..b//1, x..y//1) do
    min(a, x)..max(b, y)//1
  end

  # defp insert([{a, b} | rest], {start, ende} = se) when start >= b do
  #   [{a, b} | insert(rest, se)]
  # end

  # defp insert([{a, b} | rest], {start, ende} = se) when start < b and ende > b do
  #   insert([{a, b} | rest], {b, ende})
  # end

  # defp insert([{a, b} | rest], {start, ende} = se) when start < b and ende <= b do
  #   [{a, b} | rest]
  # end

  # defp insert([same | rest], same) do
  #   [same | rest]
  # end

  # defp insert([], se) do
  #   [se]
  # end

  # defp check_overlap({a, b}, {x, y}) when x >= a and x <= b do
  #   {:replace, {b, y}}
  # end

  # defp check_overlap({a, b}, {x, y})
end

32 = Quest2.part_one()
Quest2.part_two() |> dbg()
