defmodule AdventOfCode.Solutions.Y25.Day07Test do
  alias AdventOfCode.Solutions.Y25.Day07, as: Solution, warn: false
  alias AoC.Input, warn: false
  use ExUnit.Case, async: true

  defp solve(input, part) do
    problem =
      input
      |> Input.as_file()
      |> Solution.parse(part)

    apply(Solution, part, [problem])
  end

  test "part one example" do
    input = ~S"""
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    assert 21 == solve(input, :part_one)
  end

  @part_one_solution 1579

  test "part one solution" do
    assert {:ok, @part_one_solution} == AoC.run(2025, 7, :part_one)
  end

  test "part two example" do
    input = ~S"""
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    assert 40 == solve(input, :part_two)
  end

  @part_two_solution 13_418_215_871_354

  test "part two solution" do
    assert {:ok, @part_two_solution} == AoC.run(2025, 7, :part_two)
  end
end
